import os
from pathlib import Path
from app.core.models import ProjectType, DetectorResult

class DockerfileGenerator:
    @staticmethod
    def generate(workspace_path: Path, result: DetectorResult) -> str:
        """
        Generates a Dockerfile string based on the detected project type.
        """
        res_content = ""
        if result.project_type == ProjectType.PYTHON:
            res_content = DockerfileGenerator._generate_python(workspace_path, result)
        elif result.project_type == ProjectType.NODE:
            res_content = DockerfileGenerator._generate_node(workspace_path, result)
        elif result.project_type == ProjectType.STATIC:
            res_content = DockerfileGenerator._generate_static(workspace_path, result)
        elif result.project_type == ProjectType.JAVA:
            res_content = DockerfileGenerator._generate_java(workspace_path, result)
        elif result.project_type == ProjectType.RUBY:
            res_content = DockerfileGenerator._generate_ruby(workspace_path, result)
        elif result.project_type == ProjectType.PHP:
            res_content = DockerfileGenerator._generate_php(workspace_path, result)
        elif result.project_type == ProjectType.DOTNET:
            res_content = DockerfileGenerator._generate_dotnet(workspace_path, result)
        elif result.project_type == ProjectType.GO:
            res_content = DockerfileGenerator._generate_go(workspace_path, result)
        elif result.project_type == ProjectType.RUST:
            res_content = DockerfileGenerator._generate_rust(workspace_path, result)
        else:
            raise ValueError(f"Unsupported project type for Docker isolation: {result.project_type}")
        return f"# Generated by RepoHost\n{res_content}"

    @staticmethod
    def _generate_python(workspace_path: Path, result: DetectorResult) -> str:
        base_image = "python:3.11-slim"
        req_file = workspace_path / "requirements.txt"

        # Determine system dependencies based on requirements
        apt_deps = ["gcc", "g++", "libffi-dev", "make", "pkg-config", "sqlite3", "libsqlite3-dev"]
        
        if req_file.exists():
            reqs = req_file.read_text(encoding="utf-8", errors="ignore").lower()
            if "mariadb" in reqs or "mysql" in reqs:
                apt_deps.extend(["libmariadb-dev", "libmariadb-dev-compat", "default-libmysqlclient-dev"])
            if "psycopg2" in reqs or "postgres" in reqs:
                apt_deps.append("libpq-dev")
                
        apt_install_str = " ".join(sorted(list(set(apt_deps))))

        lines = [
            f"FROM {base_image}",
            "WORKDIR /app",
            "ENV PYTHONUNBUFFERED=1",
            "ENV FLASK_RUN_HOST=0.0.0.0",
            "COPY . /app",
            f"RUN apt-get update && apt-get install -y {apt_install_str} && rm -rf /var/lib/apt/lists/*",
        ]
        
        if req_file.exists():
            lines.append("RUN pip install --no-cache-dir --upgrade pip")
            lines.append("RUN pip install --no-cache-dir -r requirements.txt || (sed -i 's/[=<>~].*//g' requirements.txt && pip install --no-cache-dir -r requirements.txt)")
        else:
            if result.install_command:
                if len(result.install_command) > 2 and result.install_command[0] == "pip" and result.install_command[1] == "install" and "-r" not in result.install_command:
                    pkgs = " ".join(result.install_command[2:])
                    lines.append(f"RUN pip install --no-cache-dir {pkgs} || (for pkg in {pkgs}; do pip install --no-cache-dir \"$pkg\" || true; done)")
                else:
                    lines.append(f"RUN {' '.join(result.install_command)}")

        # Ensure flask-cors is available and patch hardcoded CORS origins for backend APIs
        if result.is_backend_api:
            has_cors = False
            if req_file.exists():
                has_cors = "flask-cors" in req_file.read_text(encoding="utf-8", errors="ignore").lower() or \
                           "flask_cors" in req_file.read_text(encoding="utf-8", errors="ignore").lower()
            if not has_cors:
                lines.append("RUN pip install --no-cache-dir flask-cors 2>/dev/null || true")
            # Replace hardcoded restricted CORS origins in Python files with wildcard '*'
            lines.append("RUN find /app -type f -name \"*.py\" -exec sed -i -E \"s/(\\\"origins\\\"|'origins')\\s*:\\s*(\\\"[^\\\"]+\\\"|'[^']+')/\\1: '*'/g\" {} + || true")
            lines.append("RUN find /app -type f -name \"*.py\" -exec sed -i -E \"s/allow_origins\\s*=\\s*\\[[^\\]]+\\]/allow_origins=['*']/g\" {} + || true")

        # Expose common Python web ports: 5000 (Flask), 8000 (FastAPI/Django), 8501 (Streamlit), 8080
        lines.append("EXPOSE 3000 5000 8000 8080 8501")
        
        if result.framework == "Django":
            # Ensure ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS allow localhost and Cloudflare tunnels
            lines.append('RUN python -c "from pathlib import Path; [p.write_text(p.read_text(encoding=\'utf-8\', errors=\'ignore\') + \'\\nALLOWED_HOSTS = [\\\"*\\\"]\\nCSRF_TRUSTED_ORIGINS = [\\\"https://*.trycloudflare.com\\\", \\\"http://*.trycloudflare.com\\\", \\\"http://localhost*\\\", \\\"http://127.0.0.1*\\\"]\\nCORS_ALLOW_ALL_ORIGINS = True\\nCORS_ORIGIN_ALLOW_ALL = True\\n\', encoding=\'utf-8\') for p in Path(\'.\').rglob(\'settings.py\') if not any(x in p.parts for x in (\'venv\', \'.venv\', \'__pycache__\'))]" || true')
            # Link broken signup link to /register/ if needed
            lines.append('RUN find /app/templates -type f -name "*.html" -exec sed -i \'s|href="#" class="text signup-link"|href="/register/" class="text signup-link"|g\' {} + || true')
            # Automatically apply migrations and seed a demo admin user before launching Django server
            lines.append('CMD ["sh", "-c", "python manage.py migrate --noinput || true; python manage.py shell -c \\"from django.contrib.auth import get_user_model; U = get_user_model(); U.objects.filter(is_superuser=True).exists() or U.objects.create_superuser(\'admin\', \'admin@example.com\', \'admin123\')\\" || true; python manage.py runserver 0.0.0.0:8000 --insecure"]')
        elif result.framework == "Flask":
            flask_run_cmd = " ".join(result.run_command) if result.run_command else "python -m flask run --host 0.0.0.0 --port 5000"
            seed_cmd = "python seed.py || true; " if (workspace_path / "seed.py").exists() else ""
            migrate_cmd = "flask db upgrade || true; " if (workspace_path / "migrations").is_dir() else ""
            lines.append(f'CMD ["sh", "-c", "{migrate_cmd}{seed_cmd}{flask_run_cmd}"]')
        elif result.run_command:
            cmd_str = ", ".join(f'"{c}"' for c in result.run_command)
            lines.append(f"CMD [{cmd_str}]")
            
        return "\n".join(lines)

    @staticmethod
    def _generate_node(workspace_path: Path, result: DetectorResult) -> str:
        base_image = "node:18-slim"
        
        lines = [
            f"FROM {base_image}",
            "WORKDIR /app",
            'ENV HOST="0.0.0.0"',
            "COPY package*.json ./",
        ]
        
        pkg_manager = result.package_manager or "npm"
        if pkg_manager == "yarn":
            lines.append("COPY yarn.lock ./")
            lines.append("RUN yarn install")
        elif pkg_manager == "pnpm":
            lines.append("RUN npm install -g pnpm")
            lines.append("COPY pnpm-lock.yaml ./")
            lines.append("RUN pnpm install")
        else:
            lines.append("RUN npm install")
            
        lines.append("COPY . .")
        
        # Generate Prisma client if Prisma schema exists in the project
        lines.append('RUN find /app -name "schema.prisma" -exec npx prisma generate --schema={} \\; || npx prisma generate || true')
        
        # If source URL rewriting is configured by ConnectionBridge, rewrite backend URLs in frontend source
        if hasattr(result, "source_rewrite_from") and result.source_rewrite_from and result.source_rewrite_to:
            import re
            m_from = re.search(r":(\d+)", result.source_rewrite_from)
            m_to = re.search(r":(\d+)", result.source_rewrite_to)
            port_from = m_from.group(1) if m_from else result.source_rewrite_from
            port_to = m_to.group(1) if m_to else result.source_rewrite_to
            lines.append(f'RUN find /app -not -path "*/node_modules/*" -not -path "*/.git/*" -type f \\( -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" -o -name "*.vue" -o -name "*.svelte" -o -name "*.html" -o -name "*.json" -o -name "*.env*" \\) -exec sed -i -E "s|https?://(localhost|127\\.0\\.0\\.1):{port_from}|http://localhost:{port_to}|g" {{}} + || true')
            lines.append(f'RUN find /app -not -path "*/node_modules/*" -not -path "*/.git/*" -type f \\( -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" -o -name "*.vue" -o -name "*.svelte" -o -name "*.html" -o -name "*.json" -o -name "*.env*" \\) -exec sed -i "s|{result.source_rewrite_from}|{result.source_rewrite_to}|g" {{}} + || true')
            
        # Patch hardcoded CORS origins if this Node service is a backend API
        if result.is_backend_api:
            lines.append("RUN find /app -type f \\( -name \"*.js\" -o -name \"*.ts\" \\) -exec sed -i -E \"s/origin\\s*:\\s*['\\\"][^'\\\"]+['\\\"]/origin: '*'/g\" {} + || true")
            lines.append("RUN find /app -type f \\( -name \"*.js\" -o -name \"*.ts\" \\) -exec sed -i -E \"s/origin\\s*:\\s*\\[[^\\]]+\\]/origin: '*'/g\" {} + || true")
            
        # Expose 3000 (Next/Express/Nest), 4200 (Angular), 4321 (Astro), 5173 (Vite), 8080
        lines.append("EXPOSE 3000 4000 4200 4321 5000 5173 8000 8080")
        
        if result.run_command:
            cmd_str = ", ".join(f'"{c}"' for c in result.run_command)
            lines.append(f"CMD [{cmd_str}]")
            
        return "\n".join(lines)

    @staticmethod
    def _generate_java(workspace_path: Path, result: DetectorResult) -> str:
        lines = []
        if result.package_manager == "gradle" or (workspace_path / "build.gradle").exists():
            lines = [
                "FROM gradle:8.5-jdk17",
                "WORKDIR /app",
                "COPY . /app",
                "RUN gradle build -x test || gradle assemble || true",
                "EXPOSE 8080 8000",
                'CMD ["sh", "-c", "find build/libs -name \'*.jar\' ! -name \'*plain*\' -exec java -jar {} \\; || gradle bootRun"]'
            ]
        else:
            # Default Maven
            lines = [
                "FROM maven:3.9-eclipse-temurin-17",
                "WORKDIR /app",
                "COPY . /app",
                "RUN mvn clean package -DskipTests || mvn compile || true",
                "EXPOSE 8080 8000",
                'CMD ["sh", "-c", "find target -name \'*.jar\' ! -name \'*sources*\' ! -name \'*javadoc*\' -exec java -jar {} \\; || mvn spring-boot:run"]'
            ]
        return "\n".join(lines)

    @staticmethod
    def _generate_ruby(workspace_path: Path, result: DetectorResult) -> str:
        lines = [
            "FROM ruby:3.2-slim",
            "WORKDIR /app",
            "RUN apt-get update && apt-get install -y build-essential libpq-dev sqlite3 libsqlite3-dev nodejs npm git libyaml-dev && rm -rf /var/lib/apt/lists/*",
            "COPY . /app",
            "RUN gem install bundler && bundle install || true",
        ]
        if result.framework == "Ruby on Rails":
            lines.append("RUN bundle exec rails db:prepare || bundle exec rails db:migrate || true")
            lines.append("EXPOSE 3000 8080")
            lines.append('CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]')
        else:
            lines.append("EXPOSE 3000 4567 9292 8080")
            if result.run_command:
                cmd_str = ", ".join(f'"{c}"' for c in result.run_command)
                lines.append(f"CMD [{cmd_str}]")
            else:
                lines.append('CMD ["bundle", "exec", "rackup", "-o", "0.0.0.0", "-p", "3000"]')
        return "\n".join(lines)

    @staticmethod
    def _generate_php(workspace_path: Path, result: DetectorResult) -> str:
        lines = [
            "FROM php:8.2-cli",
            "WORKDIR /app",
            "RUN apt-get update && apt-get install -y git unzip libzip-dev libsqlite3-dev libpq-dev libpng-dev libonig-dev && rm -rf /var/lib/apt/lists/*",
            "RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql zip mbstring || true",
            "COPY --from=composer:latest /usr/bin/composer /usr/bin/composer",
            "COPY . /app",
            "RUN composer install --no-interaction --prefer-dist || true",
        ]
        if result.framework == "Laravel":
            lines.append("RUN cp .env.example .env || true")
            lines.append("RUN php artisan key:generate || true")
            lines.append("EXPOSE 8000 8080")
            lines.append('CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]')
        else:
            lines.append("EXPOSE 8000 8080")
            if result.run_command:
                cmd_str = ", ".join(f'"{c}"' for c in result.run_command)
                lines.append(f"CMD [{cmd_str}]")
            else:
                lines.append('CMD ["php", "-S", "0.0.0.0:8000"]')
        return "\n".join(lines)

    @staticmethod
    def _generate_dotnet(workspace_path: Path, result: DetectorResult) -> str:
        lines = [
            "FROM mcr.microsoft.com/dotnet/sdk:8.0",
            "WORKDIR /app",
            "COPY . /app",
            "RUN dotnet restore || true",
            "ENV ASPNETCORE_URLS=http://0.0.0.0:5000",
            "EXPOSE 5000 8080",
            'CMD ["dotnet", "run", "--urls", "http://0.0.0.0:5000"]'
        ]
        return "\n".join(lines)

    @staticmethod
    def _generate_static(workspace_path: Path, result: DetectorResult) -> str:
        lines = [
            "FROM python:3.11-slim",
            "WORKDIR /app",
            "COPY . /app",
            "EXPOSE 8000"
        ]
        if result.run_command:
            run_cmd = list(result.run_command)
            if run_cmd[-1] == "0":
                run_cmd[-1] = "8000"
            cmd_str = ", ".join(f'"{c}"' for c in run_cmd)
            lines.append(f"CMD [{cmd_str}]")
            
        return "\n".join(lines)

    @staticmethod
    def _generate_go(workspace_path: Path, result: DetectorResult) -> str:
        lines = [
            "FROM golang:1.21-alpine",
            "WORKDIR /app",
            "RUN apk add --no-cache git build-base || true",
            "COPY . /app",
            "RUN if [ -f go.mod ]; then go mod download; fi",
            "EXPOSE 8080 3000 8000",
        ]
        if result.run_command:
            cmd_str = ", ".join(f'"{c}"' for c in result.run_command)
            lines.append(f"CMD [{cmd_str}]")
        else:
            lines.append('CMD ["go", "run", "."]')
        return "\n".join(lines)

    @staticmethod
    def _generate_rust(workspace_path: Path, result: DetectorResult) -> str:
        lines = [
            "FROM rust:1.75-slim",
            "WORKDIR /app",
            "COPY . /app",
            "RUN apt-get update && apt-get install -y pkg-config libssl-dev build-essential && rm -rf /var/lib/apt/lists/*",
            "RUN cargo build",
            "EXPOSE 8080 3000 8000",
        ]
        if result.run_command:
            cmd_str = ", ".join(f'"{c}"' for c in result.run_command)
            lines.append(f"CMD [{cmd_str}]")
        else:
            lines.append('CMD ["cargo", "run"]')
        return "\n".join(lines)

